[package]
name = "day2"
version = "0.1.0"
edition = "2021"
authors = [ "Kurisu<makise_kurisuu@outlook.jp>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
